version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:3.141.59-vanadium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
  app:
    build: .
    command: ruby scraping.rb
    volumes:
      - .:/app
    depends_on:
      - selenium
